platforms.config: hikey: Set TOS_PLATFORM_FLAVOR
With https://github.com/OP-TEE/optee_os/ commit
66df8a2c723c ("hikey: add support for hikey960"),
TOS_PLATFORM_FLAVOR must be set and not empty to prevent the error below:

core/arch/arm/plat-hikey/platform_config.h:60:2: error: #error Unknown console UART

Signed-off-by: Victor Chong <victor.chong@linaro.org>
Reviewed-by: Leif Lindholm <leif.lindholm@linaro.org>